### ISSUE TITLE
Error: Cannot find module 'mocha-traceur'

### ISSUE THREAD

**Issue by tekumara** [uxebu/mocha-sinon-traceur-example#1]
```
$ npm test

> mocha-with-traceur@0.0.1 test /Users/tukushan/delme/mocha-sinon-traceur-example
> mocha --compilers js:mocha-traceur src/*.js

-
module.js:340
    throw err;
          ^
Error: Cannot find module 'mocha-traceur'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at args (/Users/tukushan/delme/mocha-sinon-traceur-example/node_modules/mocha/bin/_mocha:307:3)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/tukushan/delme/mocha-sinon-traceur-example/node_modules/mocha/bin/_mocha:301:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by wolframkriesing** [comment]
thanks for finding it!
